import React, { useState, useEffect, useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import TopBar from '../components/layout/TopBar';
import { getBooks } from '../api';
import {
  BookOpen,
  FileText,
  CheckCircle2,
  Zap,
  Activity,
  RefreshCw,
  Loader2,
  Bell,
  DollarSign
} from 'lucide-react';
import toast from 'react-hot-toast';
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, Cell } from 'recharts';

const TRACK_META = {
  PMHNP:  { color:'#9B6FFF', label:'Psychiatric MH NP'    },
  FNP:    { color:'#3B6FF5', label:'Family NP'             },
  AGPCNP: { color:'#34C97A', label:'Adult-Gero PC NP'      },
  WHNP:   { color:'#F5A623', label:"Women's Health NP"     },
  AGACNP: { color:'#F5516A', label:'Adult-Gero AC NP'      },
  PNP:    { color:'#00C4C4', label:'Pediatric NP'          },
  ANP:    { color:'#7FA8FF', label:'Adult NP'              },
};
const STATUS_LABEL = {
  DRAFT:'Draft', GENERATING:'Generating', QA_PENDING:'QA Pending',
  QA_IN_PROGRESS:'QA Running', QA_PASSED:'QA Passed',
  DESIGN_PENDING:'Design Pending', DESIGN_READY:'Design Ready',
  KDP_READY:'KDP Ready', PUBLISHED:'Published',
};
const STATUS_COLOR = {
  DRAFT:'#4A5068', GENERATING:'#F5A623', QA_PENDING:'#9B6FFF', QA_IN_PROGRESS:'#9B6FFF',
  QA_PASSED:'#34C97A', DESIGN_PENDING:'#3B6FF5', DESIGN_READY:'#3B6FF5',
  KDP_READY:'#00C4C4', PUBLISHED:'#34C97A',
};

// Mock activity feed entries — in production from jobs/audit_logs table
const MOCK_ACTIVITY = [
  { id:1, type:'generating', msg:'Chapter 7: Psychopharmacology — PMHNP Book 1',    time:'2 min ago',  status:'active'  },
  { id:2, type:'qa_passed',  msg:'Chapter 6: Mood Disorders QA passed (score: 88)', time:'14 min ago', status:'success' },
  { id:3, type:'generated',  msg:'Chapter 6: Mood Disorders generated (4,812 words)', time:'18 min ago', status:'success' },
  { id:4, type:'queued',     msg:'Chapter 8: Anxiety Disorders queued for generation', time:'2 min ago', status:'info'   },
  { id:5, type:'qa_failed',  msg:'Chapter 5: Schizophrenia QA failed (score: 67) — retrying', time:'32 min ago', status:'warn' },
  { id:6, type:'generated',  msg:'Chapter 4: Neurocognitive Disorders generated (5,124 words)', time:'45 min ago', status:'success' },
];

// Mock editor flags — in production auto-generated by editorChecklistService (Phase 2)
const MOCK_FLAGS = [
  { id:1, chap:'Chapter 3', issue:'Missing Future Findings section',              severity:'CRITICAL' },
  { id:2, chap:'Chapter 5', issue:'Only 14 citations found (minimum 20 required)',severity:'CRITICAL' },
  { id:3, chap:'Chapter 7', issue:'No recent citations — all older than 4 years', severity:'CRITICAL' },
  { id:4, chap:'Chapter 9', issue:'Bold governance violation — entire paragraph bolded', severity:'WARNING' },
  { id:5, chap:'Chapter 11',issue:'Word count 3,420 — below 4,000 minimum',       severity:'WARNING' },
];

const GPT4_COST_PER_CHAPTER = 0.92;

export default function Dashboard() {
  const navigate = useNavigate();
  const [books, setBooks]     = useState([]);
  const [loading, setLoading] = useState(true);
  const activityFeed = MOCK_ACTIVITY;
  const editorFlags  = MOCK_FLAGS;
  const activityRef           = useRef(null);

  const load = async () => {
    setLoading(true);
    try {
      const [booksRes] = await Promise.allSettled([getBooks()]);
      if (booksRes.status === 'fulfilled') setBooks(booksRes.value.data?.books || booksRes.value.data || []);
    } catch { toast.error('Failed to load dashboard'); }
    finally { setLoading(false); }
  };

  useEffect(() => { load(); }, []); // eslint-disable-line

  const totalChapters  = books.reduce((s,b) => s + (b.completedChapters||0), 0);
  const publishedBooks = books.filter(b => b.status==='PUBLISHED').length;
  const activeBooks    = books.filter(b => ['GENERATING','QA_PENDING','QA_IN_PROGRESS'].includes(b.status)).length;
  const qaPassedBooks  = books.filter(b => ['QA_PASSED','DESIGN_READY','KDP_READY'].includes(b.status)).length;
  const criticalFlags  = editorFlags.filter(f => f.severity === 'CRITICAL').length;
  const estCost        = Math.round(totalChapters * GPT4_COST_PER_CHAPTER);

  const chartData = Object.entries(TRACK_META).map(([track,meta]) => ({
    name: track,
    chapters: books.filter(b => b.certificationTrack===track).reduce((s,b) => s+(b.completedChapters||0), 0),
    fill: meta.color,
  }));

  const actFeed = {
    'active':  { color:'var(--amber)',  dot:'animate-pulse' },
    'success': { color:'var(--sage)',   dot:'' },
    'warn':    { color:'var(--rose)',   dot:'' },
    'info':    { color:'var(--cobalt)', dot:'' },
  };

  return (
    <div>
      <TopBar
        title="Dashboard"
        subtitle="Zarwango–Lubega–Muyizzi Publishing · NP/DNP Textbook Engine"
        actions={
          <div style={{ display:'flex', gap:8, alignItems:'center' }}>
            {criticalFlags > 0 && (
              <div style={{ position:'relative', cursor:'pointer' }} onClick={() => { const el = document.getElementById('flag-panel'); el?.scrollIntoView({ behavior:'smooth' }); }}>
                <Bell size={16} style={{ color:'var(--rose)' }}/>
                <span style={{ position:'absolute', top:-4, right:-4, width:14, height:14, background:'var(--rose)', borderRadius:'50%', fontSize:'0.55rem', fontWeight:700, color:'#fff', display:'flex', alignItems:'center', justifyContent:'center' }}>
                  {criticalFlags}
                </span>
              </div>
            )}
            <button className="btn btn-ghost btn-sm" onClick={load} disabled={loading}>
              {loading ? <Loader2 size={13} className="animate-spin"/> : <RefreshCw size={13}/>} Refresh
            </button>
          </div>
        }
      />

      <div className="page-content stagger">
        {/* ROW 1 — KPI Stats (Bible §9.2 Row 1) */}
        <div className="stat-grid mb-6">
          <StatCard accent="blue"   Icon={BookOpen}    color="var(--cobalt)"  label="Total Books"    value={books.length}       sub="7 tracks × 4 books"/>
          <StatCard accent="green"  Icon={FileText}    color="var(--sage)"    label="Chapters Done"  value={totalChapters}      sub="all books"/>
          <StatCard accent="violet" Icon={Activity}    color="var(--violet)"  label="Active Jobs"    value={activeBooks}        sub="generating now"/>
          <StatCard accent="teal"   Icon={CheckCircle2}color="var(--teal)"    label="QA Passed"      value={qaPassedBooks}      sub="ready for design"/>
          <StatCard accent="amber"  Icon={Zap}         color="var(--amber)"   label="Published"      value={publishedBooks}     sub="live on KDP"/>
          <StatCard accent="rose"   Icon={DollarSign}  color="var(--rose)"    label="Est. Spend"     value={`$${estCost}`}      sub="GPT-4 Turbo"/>
        </div>

        {/* ROW 2 — Live Activity Feed (Bible §9.2 Row 2) */}
        <div className="card animate-fade mb-4" id="activity-feed">
          <div style={{ display:'flex', justifyContent:'space-between', alignItems:'center', padding:'14px 18px 10px' }}>
            <div>
              <h3 style={{ fontSize:'0.9rem', marginBottom:1 }}>Live Activity Feed</h3>
              <p className="text-xs text-muted">Real-time generation log</p>
            </div>
            {activeBooks > 0 && (
              <span style={{ display:'flex', alignItems:'center', gap:6, fontSize:'0.72rem', color:'var(--amber)' }} className="animate-pulse">
                <span style={{ width:7, height:7, borderRadius:'50%', background:'var(--amber)', display:'inline-block' }}/>
                {activeBooks} job{activeBooks!==1?'s':''} running
              </span>
            )}
          </div>
          <div className="divider"/>
          <div ref={activityRef} style={{ maxHeight:200, overflowY:'auto', padding:'8px 0' }}>
            {activityFeed.map(entry => {
              const ac = actFeed[entry.status] || actFeed.info;
              return (
                <div key={entry.id} style={{ display:'flex', alignItems:'flex-start', gap:12, padding:'7px 18px', borderBottom:'1px solid var(--border)' }}
                  onMouseEnter={e => e.currentTarget.style.background='var(--surface-2)'}
                  onMouseLeave={e => e.currentTarget.style.background='transparent'}>
                  <div style={{ width:7, height:7, borderRadius:'50%', background:ac.color, marginTop:5, flexShrink:0 }} className={ac.dot}/>
                  <span style={{ fontSize:'0.78rem', color:'var(--ink-700)', flex:1, lineHeight:1.4 }}>{entry.msg}</span>
                  <span style={{ fontSize:'0.65rem', color:'var(--ink-400)', flexShrink:0, fontFamily:'var(--font-mono)' }}>{entry.time}</span>
                </div>
              );
            })}
          </div>
        </div>

        {/* ROW 3 — Bundle Progress Grid (Bible §9.2 Row 3) */}
        <div className="card animate-fade mb-4">
          <div style={{ display:'flex', justifyContent:'space-between', alignItems:'center', padding:'14px 18px 8px' }}>
            <div>
              <h3 style={{ fontSize:'0.9rem' }}>28-Book Production Grid</h3>
              <p className="text-xs text-muted mt-1">Click any book to manage · Each cell shows status</p>
            </div>
            <button className="btn btn-ghost btn-xs" onClick={() => navigate('/bundle-tracker')}>Bundle View →</button>
          </div>
          <div className="divider"/>
          {loading ? (
            <div style={{ padding:40, textAlign:'center' }}><Loader2 size={24} className="animate-spin" style={{ color:'var(--cobalt)' }}/></div>
          ) : books.length === 0 ? (
            <div className="empty-state">
              <BookOpen size={28}/>
              <h3>No books yet</h3>
              <p>Use New Book to create your catalog</p>
              <button className="btn btn-primary btn-sm" onClick={() => navigate('/new-book')}><Zap size={13}/> New Book</button>
            </div>
          ) : (
            <div style={{ padding:'12px 18px 16px' }}>
              {Object.entries(TRACK_META).map(([track,meta]) => {
                const trackBooks = books.filter(b => b.certificationTrack === track);
                if (!trackBooks.length) return null;
                return (
                  <div key={track} style={{ marginBottom:12 }}>
                    <div style={{ display:'flex', alignItems:'center', gap:8, marginBottom:7 }}>
                      <div style={{ width:8, height:8, borderRadius:'50%', background:meta.color }}/>
                      <span style={{ fontSize:'0.76rem', fontWeight:700, color:'var(--ink-700)', fontFamily:'var(--font-display)' }}>{track}</span>
                      <span style={{ fontSize:'0.62rem', color:'var(--ink-500)' }}>— {meta.label}</span>
                      <span style={{ fontSize:'0.62rem', color:'var(--ink-300)', marginLeft:'auto', fontFamily:'var(--font-mono)' }}>
                        {trackBooks.filter(b=>b.status==='PUBLISHED').length}/{trackBooks.length} published
                      </span>
                    </div>
                    <div style={{ display:'flex', gap:7, flexWrap:'wrap' }}>
                      {[1,2,3,4].map(num => {
                        const book = trackBooks.find(b => b.trackNumber === num);
                        return <BookCell key={num} book={book} num={num} color={meta.color} onClick={() => book && navigate(`/books/${book.id}`)}/>;
                      })}
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </div>

        {/* ROW 4 — Editor Checklist / Flag Panel (Bible §9.2 Row 4, §9.3) */}
        <div className="card animate-fade mb-4" id="flag-panel">
          <div style={{ display:'flex', justifyContent:'space-between', alignItems:'center', padding:'14px 18px 10px' }}>
            <div>
              <h3 style={{ fontSize:'0.9rem', marginBottom:1 }}>
                🚩 Editor Checklist — Flag Panel
                {criticalFlags > 0 && (
                  <span style={{ marginLeft:10, padding:'2px 8px', background:'rgba(245,81,106,0.15)', color:'var(--rose)', borderRadius:'var(--r-pill)', fontSize:'0.65rem', fontWeight:700 }}>
                    {criticalFlags} critical
                  </span>
                )}
              </h3>
              <p className="text-xs text-muted">Auto-detected issues in currently generating book: PMHNP Book 1</p>
            </div>
            <span style={{ fontSize:'0.68rem', color:'var(--ink-400)' }}>Phase 2 will auto-trigger on every generation</span>
          </div>
          <div className="divider"/>
          <div style={{ padding:'8px 0' }}>
            {editorFlags.length === 0 ? (
              <div style={{ padding:'16px 18px', display:'flex', alignItems:'center', gap:8 }}>
                <CheckCircle2 size={14} style={{ color:'var(--sage)' }}/>
                <span style={{ fontSize:'0.78rem', color:'var(--sage)' }}>All checks passing — no issues detected</span>
              </div>
            ) : editorFlags.map(flag => (
              <div key={flag.id} style={{
                display:'flex', alignItems:'center', gap:12, padding:'8px 18px',
                borderBottom:'1px solid var(--border)',
                background: flag.severity==='CRITICAL' ? 'rgba(245,81,106,0.03)' : 'transparent',
              }}
                onMouseEnter={e => e.currentTarget.style.background='var(--surface-2)'}
                onMouseLeave={e => e.currentTarget.style.background = flag.severity==='CRITICAL'?'rgba(245,81,106,0.03)':'transparent'}
              >
                <span style={{ fontSize:'0.88rem' }}>{flag.severity === 'CRITICAL' ? '❌' : '⚠️'}</span>
                <span style={{ fontSize:'0.72rem', fontWeight:600, color:'var(--ink-500)', minWidth:80, flexShrink:0 }}>{flag.chap}:</span>
                <span style={{ fontSize:'0.78rem', color: flag.severity==='CRITICAL'?'var(--rose)':'var(--amber)', flex:1 }}>{flag.issue}</span>
                <span style={{ fontSize:'0.65rem', padding:'2px 7px', borderRadius:'var(--r-pill)',
                  background: flag.severity==='CRITICAL'?'rgba(245,81,106,0.12)':'rgba(245,166,35,0.12)',
                  color: flag.severity==='CRITICAL'?'var(--rose)':'var(--amber)', flexShrink:0, fontWeight:600
                }}>
                  {flag.severity}
                </span>
              </div>
            ))}
          </div>
        </div>

        {/* ROW 5 — Track Progress Bars (Bible §9.2 Row 5) */}
        <div style={{ display:'grid', gridTemplateColumns:'1fr 340px', gap:16, marginBottom:16 }}>
          <div className="card animate-fade">
            <div className="card-pad" style={{ paddingBottom:8 }}>
              <h3 style={{ fontSize:'0.88rem', marginBottom:2 }}>Track Progress</h3>
              <p className="text-xs text-muted">Chapters complete per certification track</p>
            </div>
            <div style={{ padding:'12px 18px 16px' }}>
              {Object.entries(TRACK_META).map(([track, meta]) => {
                const trackBooks = books.filter(b => b.certificationTrack === track);
                const done  = trackBooks.reduce((s,b) => s + (b.completedChapters||0), 0);
                const total = trackBooks.reduce((s,b) => s + (b.totalChapters||0), 0);
                const pct   = total ? Math.round((done/total)*100) : 0;
                return (
                  <div key={track} style={{ marginBottom:10 }}>
                    <div style={{ display:'flex', justifyContent:'space-between', marginBottom:4 }}>
                      <span style={{ fontSize:'0.75rem', fontWeight:600, color:'var(--ink-700)' }}>{track}</span>
                      <span style={{ fontSize:'0.68rem', fontFamily:'var(--font-mono)', color:'var(--ink-500)' }}>
                        {done}/{total} ch · {pct}%
                      </span>
                    </div>
                    <div className="progress-bar" style={{ height:6 }}>
                      <div className="progress-fill" style={{ width:`${pct}%`, background:meta.color }}/>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>

          {/* ROW 6 — Cost Tracker (Bible §9.2 Row 6) */}
          <div className="card animate-fade">
            <div className="card-pad" style={{ paddingBottom:10 }}>
              <h3 style={{ fontSize:'0.88rem', marginBottom:2 }}>Cost Tracker</h3>
              <p className="text-xs text-muted">Tokens used · Estimated spend</p>
            </div>
            <div className="divider"/>
            <div style={{ padding:'14px 18px' }}>
              <div style={{ marginBottom:14 }}>
                <div style={{ display:'flex', justifyContent:'space-between', marginBottom:5 }}>
                  <span style={{ fontSize:'0.72rem', color:'var(--ink-500)' }}>Monthly budget</span>
                  <span style={{ fontSize:'0.72rem', fontFamily:'var(--font-mono)', color:'var(--ink-700)' }}>$400</span>
                </div>
                <div className="progress-bar" style={{ height:8 }}>
                  <div className="progress-fill" style={{
                    width:`${Math.min(Math.round((estCost/400)*100),100)}%`,
                    background: estCost > 320 ? 'var(--rose)' : estCost > 240 ? 'var(--amber)' : 'var(--sage)',
                  }}/>
                </div>
                <div style={{ display:'flex', justifyContent:'space-between', marginTop:4 }}>
                  <span style={{ fontSize:'0.65rem', color:'var(--ink-400)' }}>${estCost} used</span>
                  <span style={{ fontSize:'0.65rem', color:'var(--ink-400)' }}>${400 - estCost} remaining</span>
                </div>
              </div>

              {[
                { label:'Est. input tokens',  val:`${Math.round(totalChapters*12)}K` },
                { label:'Est. output tokens', val:`${Math.round(totalChapters*8)}K`  },
                { label:'Cost / chapter',     val:'~$0.92'                            },
                { label:'Projected (28 bks)', val:`$${Math.round(28*18*0.92)}`       },
              ].map(row => (
                <div key={row.label} style={{ display:'flex', justifyContent:'space-between', marginBottom:6 }}>
                  <span style={{ fontSize:'0.72rem', color:'var(--ink-500)' }}>{row.label}</span>
                  <span style={{ fontSize:'0.73rem', fontFamily:'var(--font-mono)', fontWeight:600, color:'var(--ink-700)' }}>{row.val}</span>
                </div>
              ))}

              <button className="btn btn-ghost btn-xs w-full mt-2" onClick={() => navigate('/analytics')} style={{ justifyContent:'center' }}>
                Full Analytics →
              </button>
            </div>
          </div>
        </div>

        {/* Charts row */}
        <div className="card animate-fade">
          <div className="card-pad" style={{ paddingBottom:8 }}>
            <h3 style={{ fontSize:'0.88rem', marginBottom:2 }}>Chapters Generated by Track</h3>
          </div>
          <div style={{ padding:'4px 8px 16px' }}>
            <ResponsiveContainer width="100%" height={160}>
              <BarChart data={chartData} barCategoryGap="30%">
                <XAxis dataKey="name" tick={{ fontSize:10, fill:'#8892AA' }} axisLine={false} tickLine={false}/>
                <YAxis tick={{ fontSize:10, fill:'#8892AA' }} axisLine={false} tickLine={false}/>
                <Tooltip contentStyle={{ background:'#161B2E', border:'1px solid rgba(255,255,255,0.1)', borderRadius:8, fontSize:12 }} cursor={{ fill:'rgba(255,255,255,0.04)' }}/>
                <Bar dataKey="chapters" radius={[4,4,0,0]}>
                  {chartData.map((e,i) => <Cell key={i} fill={e.fill} fillOpacity={0.85}/>)}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>
    </div>
  );
}

function StatCard({ accent, Icon, color, label, value, sub }) {
  return (
    <div className={`stat-card accent-${accent}`}>
      <div className="stat-icon" style={{ background:`${color}18` }}><Icon size={16} style={{ color }}/></div>
      <div className="stat-value" style={{ color }}>{value}</div>
      <div className="stat-label">{label}</div>
      {sub && <div className="stat-delta">{sub}</div>}
    </div>
  );
}

function BookCell({ book, num, color, onClick }) {
  if (!book) return (
    <div style={{ width:95, padding:'7px 9px', background:'var(--surface-2)', border:'1px dashed var(--border)', borderRadius:'var(--r-sm)', opacity:0.4 }}>
      <div style={{ fontSize:'0.6rem', color:'var(--ink-300)' }}>Book {num}</div>
      <div style={{ fontSize:'0.7rem', color:'var(--ink-400)', marginTop:2 }}>—</div>
    </div>
  );
  const sc = STATUS_COLOR[book.status] || '#4A5068';
  const pct = book.totalChapters ? Math.round((book.completedChapters/book.totalChapters)*100) : 0;
  return (
    <div onClick={onClick} title={book.title}
      style={{ width:95, padding:'7px 9px', background:'var(--surface-2)', border:`1px solid ${sc}35`, borderRadius:'var(--r-sm)', cursor:'pointer', transition:'all 0.15s', position:'relative', overflow:'hidden' }}
      onMouseEnter={e => { e.currentTarget.style.borderColor=sc; e.currentTarget.style.background=`${sc}10`; }}
      onMouseLeave={e => { e.currentTarget.style.borderColor=`${sc}35`; e.currentTarget.style.background='var(--surface-2)'; }}>
      <div style={{ position:'absolute', top:0, left:0, right:0, height:2, background:sc }}/>
      <div style={{ fontSize:'0.58rem', color:'var(--ink-400)', marginBottom:2 }}>Book {num}</div>
      <div style={{ fontSize:'0.65rem', color:sc, fontWeight:600, marginBottom:3 }}>{STATUS_LABEL[book.status]||book.status}</div>
      <div style={{ height:3, background:'var(--surface-3)', borderRadius:2, overflow:'hidden' }}>
        <div style={{ height:'100%', width:`${pct}%`, background:sc }}/>
      </div>
      <div style={{ fontSize:'0.56rem', color:'var(--ink-400)', marginTop:2 }}>{book.completedChapters||0}/{book.totalChapters||0} ch</div>
    </div>
  );
}
